### ISSUE TITLE
爬到语音会中断

### ISSUE THREAD

**Issue by notilus67** [cnwangjihe/TiebaBackup#1]
```
[!] ERROR: 发生异常:
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    FileHandle.write(GetPost(pid,lz,comment))
  File "main.py", line 224, in GetPost
    Write(ProcessFloor(floor["floor"],userlist[floor["author_id"]]["name"],flo
or["time"],ProcessContent(floor["content"],0)))
  File "main.py", line 181, in ProcessContent
    raise UndifiedMsgType("content data wrong: \n%s\n"%str(s))
UndifiedMsgType: content data wrong:
{'type': '10', 'during_time': '17000', 'voice_md5': '9f465d794344d72fb8e19b74b
fef11e1_1078292675'}
```
楼层或楼中楼遇到语音会中断作业，建议……跳过?

**Comment by cnwangjihe** [comment]
才发现贴吧还有视频和音频,暂时改成warning
视频加上了,但音频还有点问题,只有一个voice_md5,
我这几天再看看怎么得到链接

**Comment by cnwangjihe** [comment]
已经把视频音频都搞定了,现在用html会更好,
但百度的语音是AMR格式的,html5不支持,
现在的方案就是如果需要在html内嵌播放的话,
就需要ffmpeg转
不然就保留AMR格式,在html上放一个链接
暂时就这样,好像也没有更好的方案
